insert into ab_user values(1,'admin','user','admin','pbkdf2:sha1:1000$szrobnh7$3217dfa97fd183b69f207a7829a61bbd1300591d',1,'admin@fab.org','2016-12-23 11:02:29.474892',7,0,'2016-11-17 20:32:25.452827','2016-11-17 20:32:25.452864',null,null);
insert into ab_user values(2,'superset','jinjy','superset','pbkdf2:sha1:1000$qyoiysi7$669dd91df94162c2c84b9f0153cc776c11a27c49',1,'16110505@cnsuning.com','2017-01-22 14:06:02.424812',12,0,'2016-12-14 17:53:40.937795','2016-12-14 18:54:43.259585',null,1);
insert into ab_view_menu values(1,'myindexview');
insert into ab_view_menu values(2,'utilview');
insert into ab_view_menu values(3,'localeview');
insert into ab_view_menu values(4,'resetpasswordview');
insert into ab_view_menu values(5,'resetmypasswordview');
insert into ab_view_menu values(6,'userinfoeditview');
insert into ab_view_menu values(7,'authdbview');
insert into ab_view_menu values(8,'userdbmodelview');
insert into ab_view_menu values(9,'list users');
insert into ab_view_menu values(10,'security');
insert into ab_view_menu values(11,'rolemodelview');
insert into ab_view_menu values(12,'list roles');
insert into ab_view_menu values(13,'userstatschartview');
insert into ab_view_menu values(14,'user''s statistics');
insert into ab_view_menu values(15,'permissionmodelview');
insert into ab_view_menu values(16,'base permissions');
insert into ab_view_menu values(17,'viewmenumodelview');
insert into ab_view_menu values(18,'views/menus');
insert into ab_view_menu values(19,'permissionviewmodelview');
insert into ab_view_menu values(20,'permission on views/menus');
insert into ab_view_menu values(21,'tablecolumninlineview');
insert into ab_view_menu values(22,'druidcolumninlineview');
insert into ab_view_menu values(23,'sqlmetricinlineview');
insert into ab_view_menu values(24,'druidmetricinlineview');
insert into ab_view_menu values(25,'import dashboards');
insert into ab_view_menu values(26,'manage');
insert into ab_view_menu values(27,'databaseview');
insert into ab_view_menu values(28,'databases');
insert into ab_view_menu values(29,'sources');
insert into ab_view_menu values(30,'databaseasync');
insert into ab_view_menu values(31,'databasetablesasync');
insert into ab_view_menu values(32,'tablemodelview');
insert into ab_view_menu values(33,'tables');
insert into ab_view_menu values(34,'accessrequestsmodelview');
insert into ab_view_menu values(35,'access requests');
insert into ab_view_menu values(36,'druidclustermodelview');
insert into ab_view_menu values(37,'druid clusters');
insert into ab_view_menu values(38,'slicemodelview');
insert into ab_view_menu values(39,'slices');
insert into ab_view_menu values(40,'sliceasync');
insert into ab_view_menu values(41,'sliceaddview');
insert into ab_view_menu values(42,'dashboardmodelview');
insert into ab_view_menu values(43,'dashboards');
insert into ab_view_menu values(44,'dashboardmodelviewasync');
insert into ab_view_menu values(45,'logmodelview');
insert into ab_view_menu values(46,'action log');
insert into ab_view_menu values(47,'druiddatasourcemodelview');
insert into ab_view_menu values(48,'druid datasources');
insert into ab_view_menu values(49,'r');
insert into ab_view_menu values(50,'superset');
insert into ab_view_menu values(51,'refresh druid metadata');
insert into ab_view_menu values(52,'csstemplatemodelview');
insert into ab_view_menu values(53,'css templates');
insert into ab_view_menu values(54,'csstemplateasyncmodelview');
insert into ab_view_menu values(55,'sql editor');
insert into ab_view_menu values(56,'sql lab');
insert into ab_view_menu values(57,'query search');
insert into ab_view_menu values(58,'all_datasource_access');
insert into ab_view_menu values(65,'[main].(id:1)');
insert into ab_view_menu values(66,'[druid cluster].(id:none)');
insert into ab_view_menu values(67,'[druid cluster].(id:1)');
insert into ab_view_menu values(68,'queryview');
insert into ab_view_menu values(69,'queries');
insert into ab_view_menu values(70,'all_database_access');
insert into ab_view_menu values(71,'[druid cluster].[copa_fi_sum_td](id:1)');
insert into ab_view_menu values(72,'[druid cluster].[druid_metrics](id:2)');
insert into ab_view_menu values(73,'[druid cluster].[gmv-json-long-1](id:3)');
insert into ab_view_menu values(74,'[druid cluster].[gmv-json-long-month-day](id:4)');
insert into ab_view_menu values(75,'[druid cluster].[huatuo_gauges](id:5)');
insert into ab_view_menu values(76,'[druid cluster].[metrics-kafka](id:6)');
insert into ab_view_menu values(77,'[druid cluster].[minos2](id:7)');
insert into ab_view_menu values(78,'[druid cluster].[pageviews-kafka](id:8)');
insert into ab_view_menu values(79,'[druid cluster].[retail](id:9)');
insert into ab_view_menu values(80,'[druid cluster].[traffic](id:10)');
insert into ab_view_menu values(81,'[druid cluster].[traffic-parquet](id:11)');
insert into ab_view_menu values(82,'[druid cluster].[bi-dfp-oms-detail](id:12)');
insert into ab_view_menu values(83,'[druid cluster].[bi-dfp-oms-detail-uncompressed](id:13)');
insert into ab_view_menu values(84,'[druid cluster].[day_bi-dfp-oms-detail](id:14)');
insert into ab_view_menu values(85,'[druid cluster].[hbase_metrics](id:15)');
insert into ab_view_menu values(86,'[druid cluster].[huatuo_events](id:16)');
insert into ab_view_menu values(87,'[druid cluster].[huatuo_timers](id:17)');
insert into ab_view_menu values(88,'[druid cluster].[minute_bi-dfp-oms-detail](id:18)');
insert into ab_view_menu values(89,'[druid cluster].[test1day_bi-dfp-oms-detail](id:19)');
insert into ab_view_menu values(90,'[druid cluster].[test2day_bi-dfp-oms-detail](id:20)');
insert into ab_view_menu values(91,'[druid cluster].[testday_bi-dfp-oms-detail](id:21)');
insert into ab_view_menu values(92,'[druid cluster].[yingyan_goods_druid_sit2](id:22)');
insert into ab_view_menu values(93,'[druid cluster].[yingyan_goods_druid_sit4](id:23)');
insert into ab_view_menu values(94,'[druid cluster].[yingyan_goods_druid_sit5](id:24)');
insert into ab_view_menu values(95,'[druid cluster].[yingyan_goods_druid_sit6](id:25)');
insert into ab_role values(1,'admin');
insert into ab_role values(2,'public');
insert into ab_role values(3,'alpha');