INSERT INTO ab_user VALUES(1,'admin','user','admin','pbkdf2:sha1:1000$sZRobnh7$3217dfa97fd183b69f207a7829a61bbd1300591d',1,'admin@fab.org','2016-12-23 11:02:29.474892',7,0,'2016-11-17 20:32:25.452827','2016-11-17 20:32:25.452864',NULL,NULL);
INSERT INTO ab_user VALUES(2,'superset','jinjy','superset','pbkdf2:sha1:1000$qyOiYsI7$669dd91df94162c2c84b9f0153cc776c11a27c49',1,'16110505@yuzhouwan.com','2017-01-22 14:06:02.424812',12,0,'2016-12-14 17:53:40.937795','2016-12-14 18:54:43.259585',NULL,1);
INSERT INTO ab_view_menu VALUES(1,'MyIndexView');
INSERT INTO ab_view_menu VALUES(2,'UtilView');
INSERT INTO ab_view_menu VALUES(3,'LocaleView');
INSERT INTO ab_view_menu VALUES(4,'ResetPasswordView');
INSERT INTO ab_view_menu VALUES(5,'ResetMyPasswordView');
INSERT INTO ab_view_menu VALUES(6,'UserInfoEditView');
INSERT INTO ab_view_menu VALUES(7,'AuthDBView');
INSERT INTO ab_view_menu VALUES(8,'UserDBModelView');
INSERT INTO ab_view_menu VALUES(9,'List Users');
INSERT INTO ab_view_menu VALUES(10,'Security');
INSERT INTO ab_view_menu VALUES(11,'RoleModelView');
INSERT INTO ab_view_menu VALUES(12,'List Roles');
INSERT INTO ab_view_menu VALUES(13,'UserStatsChartView');
INSERT INTO ab_view_menu VALUES(14,'User''s Statistics');
INSERT INTO ab_view_menu VALUES(15,'PermissionModelView');
INSERT INTO ab_view_menu VALUES(16,'Base Permissions');
INSERT INTO ab_view_menu VALUES(17,'ViewMenuModelView');
INSERT INTO ab_view_menu VALUES(18,'Views/Menus');
INSERT INTO ab_view_menu VALUES(19,'PermissionViewModelView');
INSERT INTO ab_view_menu VALUES(20,'Permission on Views/Menus');
INSERT INTO ab_view_menu VALUES(21,'TableColumnInlineView');
INSERT INTO ab_view_menu VALUES(22,'DruidColumnInlineView');
INSERT INTO ab_view_menu VALUES(23,'SqlMetricInlineView');
INSERT INTO ab_view_menu VALUES(24,'DruidMetricInlineView');
INSERT INTO ab_view_menu VALUES(25,'Import Dashboards');
INSERT INTO ab_view_menu VALUES(26,'Manage');
INSERT INTO ab_view_menu VALUES(27,'DatabaseView');
INSERT INTO ab_view_menu VALUES(28,'Databases');
INSERT INTO ab_view_menu VALUES(29,'Sources');
INSERT INTO ab_view_menu VALUES(30,'DatabaseAsync');
INSERT INTO ab_view_menu VALUES(31,'DatabaseTablesAsync');
INSERT INTO ab_view_menu VALUES(32,'TableModelView');
INSERT INTO ab_view_menu VALUES(33,'Tables');
INSERT INTO ab_view_menu VALUES(34,'AccessRequestsModelView');
INSERT INTO ab_view_menu VALUES(35,'Access requests');
INSERT INTO ab_view_menu VALUES(36,'DruidClusterModelView');
INSERT INTO ab_view_menu VALUES(37,'Druid Clusters');
INSERT INTO ab_view_menu VALUES(38,'SliceModelView');
INSERT INTO ab_view_menu VALUES(39,'Slices');
INSERT INTO ab_view_menu VALUES(40,'SliceAsync');
INSERT INTO ab_view_menu VALUES(41,'SliceAddView');
INSERT INTO ab_view_menu VALUES(42,'DashboardModelView');
INSERT INTO ab_view_menu VALUES(43,'Dashboards');
INSERT INTO ab_view_menu VALUES(44,'DashboardModelViewAsync');
INSERT INTO ab_view_menu VALUES(45,'LogModelView');
INSERT INTO ab_view_menu VALUES(46,'Action Log');
INSERT INTO ab_view_menu VALUES(47,'DruidDatasourceModelView');
INSERT INTO ab_view_menu VALUES(48,'Druid Datasources');
INSERT INTO ab_view_menu VALUES(49,'R');
INSERT INTO ab_view_menu VALUES(50,'Superset');
INSERT INTO ab_view_menu VALUES(51,'Refresh Druid Metadata');
INSERT INTO ab_view_menu VALUES(52,'CssTemplateModelView');
INSERT INTO ab_view_menu VALUES(53,'CSS Templates');
INSERT INTO ab_view_menu VALUES(54,'CssTemplateAsyncModelView');
INSERT INTO ab_view_menu VALUES(55,'SQL Editor');
INSERT INTO ab_view_menu VALUES(56,'SQL Lab');
INSERT INTO ab_view_menu VALUES(57,'Query Search');
INSERT INTO ab_view_menu VALUES(58,'all_datasource_access');
INSERT INTO ab_view_menu VALUES(59,'[main].[energy_usage](id:1)');
INSERT INTO ab_view_menu VALUES(60,'[main].[wb_health_population](id:2)');
INSERT INTO ab_view_menu VALUES(61,'[main].[birth_names](id:3)');
INSERT INTO ab_view_menu VALUES(62,'[main].[random_time_series](id:4)');
INSERT INTO ab_view_menu VALUES(63,'[main].[long_lat](id:5)');
INSERT INTO ab_view_menu VALUES(64,'[main].[multiformat_time_series](id:6)');
INSERT INTO ab_view_menu VALUES(65,'[main].(id:1)');
INSERT INTO ab_view_menu VALUES(66,'[druid cluster].(id:None)');
INSERT INTO ab_view_menu VALUES(67,'[druid cluster].(id:1)');
INSERT INTO ab_view_menu VALUES(68,'QueryView');
INSERT INTO ab_view_menu VALUES(69,'Queries');
INSERT INTO ab_view_menu VALUES(70,'all_database_access');
INSERT INTO ab_view_menu VALUES(71,'[druid cluster].[copa_fi_sum_td](id:1)');
INSERT INTO ab_view_menu VALUES(72,'[druid cluster].[druid_metrics](id:2)');
INSERT INTO ab_view_menu VALUES(73,'[druid cluster].[gmv-json-long-1](id:3)');
INSERT INTO ab_view_menu VALUES(74,'[druid cluster].[gmv-json-long-month-day](id:4)');
INSERT INTO ab_view_menu VALUES(75,'[druid cluster].[huatuo_gauges](id:5)');
INSERT INTO ab_view_menu VALUES(76,'[druid cluster].[metrics-kafka](id:6)');
INSERT INTO ab_view_menu VALUES(77,'[druid cluster].[minos2](id:7)');
INSERT INTO ab_view_menu VALUES(78,'[druid cluster].[pageviews-kafka](id:8)');
INSERT INTO ab_view_menu VALUES(79,'[druid cluster].[retail](id:9)');
INSERT INTO ab_view_menu VALUES(80,'[druid cluster].[traffic](id:10)');
INSERT INTO ab_view_menu VALUES(81,'[druid cluster].[traffic-parquet](id:11)');
INSERT INTO ab_view_menu VALUES(82,'[druid cluster].[bi-dfp-oms-detail](id:12)');
INSERT INTO ab_view_menu VALUES(83,'[druid cluster].[bi-dfp-oms-detail-uncompressed](id:13)');
INSERT INTO ab_view_menu VALUES(84,'[druid cluster].[day_bi-dfp-oms-detail](id:14)');
INSERT INTO ab_view_menu VALUES(85,'[druid cluster].[hbase_metrics](id:15)');
INSERT INTO ab_view_menu VALUES(86,'[druid cluster].[huatuo_events](id:16)');
INSERT INTO ab_view_menu VALUES(87,'[druid cluster].[huatuo_timers](id:17)');
INSERT INTO ab_view_menu VALUES(88,'[druid cluster].[minute_bi-dfp-oms-detail](id:18)');
INSERT INTO ab_view_menu VALUES(89,'[druid cluster].[test1day_bi-dfp-oms-detail](id:19)');
INSERT INTO ab_view_menu VALUES(90,'[druid cluster].[test2day_bi-dfp-oms-detail](id:20)');
INSERT INTO ab_view_menu VALUES(91,'[druid cluster].[testday_bi-dfp-oms-detail](id:21)');
INSERT INTO ab_view_menu VALUES(92,'[druid cluster].[yingyan_goods_druid_sit2](id:22)');
INSERT INTO ab_view_menu VALUES(93,'[druid cluster].[yingyan_goods_druid_sit4](id:23)');
INSERT INTO ab_view_menu VALUES(94,'[druid cluster].[yingyan_goods_druid_sit5](id:24)');
INSERT INTO ab_view_menu VALUES(95,'[druid cluster].[yingyan_goods_druid_sit6](id:25)');
INSERT INTO ab_role VALUES(1,'Admin');
INSERT INTO ab_role VALUES(2,'Public');
INSERT INTO ab_role VALUES(3,'Alpha');