## producer basic ##
kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
kafka.acks=0
kafka.batch.size=16384
kafka.linger.ms=5000
kafka.buffer.memory=33554432
kafka.send.buffer.bytes=102400
## producer performance ##
#kafka.acks=1
#kafka.batch.size=1048576
#kafka.linger.ms=1000
#kafka.buffer.memory=134217728
#kafka.send.buffer.bytes=8388608
