name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker -D build -t yuzhouwan:1.1.1-SNAPSHOT -f distribution/docker/Dockerfile .
