name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.ipynb'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.ipynb'
      - '.gitignore'

jobs:
  build:
    name: Run all of test cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven target
        uses: actions/cache@v2
        with:
          path: '**/target'
          key: maven-target-${{ runner.os }}-${{ github.sha }}
          restore-keys: maven-target-${{ runner.os }}-

      - name: Test with Maven
        run: mvn clean install -T 1C
